"""criacao inicial das tabelas

Revision ID: 7ccf1216afdc
Revises: 
Create Date: 2026-06-26 19:28:14.569289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ccf1216afdc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto',
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_produto'))
    )
    op.create_table('unidade',
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('regiao_cidade', sa.String(length=255), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('ativa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unidade'))
    )
    op.create_table('produto_unidade',
    sa.Column('produto_id', sa.BigInteger(), nullable=False),
    sa.Column('unidade_id', sa.BigInteger(), nullable=False),
    sa.Column('quantidade_estoque', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], name=op.f('fk_produto_unidade_produto_id_produto')),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidade.id'], name=op.f('fk_produto_unidade_unidade_id_unidade')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_produto_unidade')),
    sa.UniqueConstraint('produto_id', 'unidade_id', name='uq_produto_unidade')
    )
    op.create_table('usuario',
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.Enum('super_admin', 'admin', 'gerente', 'cozinha', 'atendente', 'cliente', name='perfilusuario', native_enum=False, length=50), nullable=False),
    sa.Column('unidade_id', sa.BigInteger(), nullable=True),
    sa.Column('consentimento_lgpd', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('consentimento_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidade.id'], name=op.f('fk_usuario_unidade_id_unidade')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario'))
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('usuario_id', sa.BigInteger(), nullable=True),
    sa.Column('acao', sa.String(length=255), nullable=False),
    sa.Column('entidade', sa.String(length=255), nullable=False),
    sa.Column('entidade_id', sa.BigInteger(), nullable=True),
    sa.Column('detalhe', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_audit_log_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('pedido',
    sa.Column('cliente_id', sa.BigInteger(), nullable=False),
    sa.Column('unidade_id', sa.BigInteger(), nullable=False),
    sa.Column('canal_pedido', sa.Enum('app', 'totem', 'balcao', 'pickup', 'web', name='canalpedido', native_enum=False, length=50), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'confirmado', 'em_preparo', 'pronto', 'em_entrega', 'entregue', 'cancelado', name='statuspedido', native_enum=False, length=50), server_default='pendente', nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuario.id'], name=op.f('fk_pedido_cliente_id_usuario')),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidade.id'], name=op.f('fk_pedido_unidade_id_unidade')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pedido'))
    )
    op.create_table('item_pedido',
    sa.Column('pedido_id', sa.BigInteger(), nullable=False),
    sa.Column('produto_id', sa.BigInteger(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], name=op.f('fk_item_pedido_pedido_id_pedido')),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], name=op.f('fk_item_pedido_produto_id_produto')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_pedido'))
    )
    op.create_table('movimentacao_pontos',
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('pedido_id', sa.BigInteger(), nullable=True),
    sa.Column('tipo', sa.Enum('credito', 'debito', 'estorno', 'expiracao', name='tipomovimentacaopontos', native_enum=False, length=50), nullable=False),
    sa.Column('pontos', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], name=op.f('fk_movimentacao_pontos_pedido_id_pedido')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_movimentacao_pontos_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimentacao_pontos'))
    )
    op.create_table('pagamento',
    sa.Column('pedido_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'processando', 'aprovado', 'recusado', 'estornado', 'cancelado', name='statuspagamento', native_enum=False, length=50), server_default='pendente', nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('referencia_externa', sa.String(length=255), nullable=True),
    sa.Column('processado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], name=op.f('fk_pagamento_pedido_id_pedido')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pagamento')),
    sa.UniqueConstraint('pedido_id', name=op.f('uq_pagamento_pedido_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagamento')
    op.drop_table('movimentacao_pontos')
    op.drop_table('item_pedido')
    op.drop_table('pedido')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('produto_unidade')
    op.drop_table('unidade')
    op.drop_table('produto')
    # ### end Alembic commands ###
